baseURL = "http://example.org/"
languageCode = "en-us"
title = "Mon"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Some things about me"
  facebook = ""
  twitter = "https://twitter.com/Akenaide"
  instagram = ""
  youtube = ""
  github = "https://github.com/Akenaide"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/kevin-man-sang-7788aa149/"
  mastodon = ""
  background_color_class = "bg-green"

[languages]
  [languages.en]
    weight = 1
  [languages.fr]
    weight = 2
  [languages.ja]
    title = "門(Mon)"
    weight = 3
